import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";
const cliOnly = process.argv.includes("--cli");
const watch = process.argv.includes("--watch");

// Plugin build — outputs main.js for Obsidian
const pluginBuild = {
  banner: { js: banner },
  entryPoints: ["src/plugin/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  platform: "node",
};

// CLI build — outputs dist/cli.js for standalone usage
const cliBuild = {
  banner: { js: "#!/usr/bin/env node\n" + banner },
  entryPoints: ["src/cli/cli.ts"],
  bundle: true,
  external: [...builtins],
  format: "esm",
  target: "es2022",
  logLevel: "info",
  sourcemap: false,
  treeShaking: true,
  outfile: "dist/cli.js",
  minify: prod,
  platform: "node",
};

async function build() {
  if (cliOnly) {
    if (watch) {
      const ctx = await esbuild.context(cliBuild);
      await ctx.watch();
    } else {
      await esbuild.build(cliBuild);
    }
  } else if (watch) {
    const ctx1 = await esbuild.context(pluginBuild);
    const ctx2 = await esbuild.context(cliBuild);
    await Promise.all([ctx1.watch(), ctx2.watch()]);
  } else {
    await Promise.all([
      esbuild.build(pluginBuild),
      esbuild.build(cliBuild),
    ]);
  }
}

build().catch(() => process.exit(1));
